name: CI

on:
  push:
  pull_request:
    branches:
      - add-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: make install

      - name: Set up environment variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV

      - name: Run Rubocop and Slim lint
        run: make lint
      
      - name: Run test
        run: make test
